use crate::Characters;

/// At this indicated position Rotor I will also step the next rotor in
/// sequence.
pub(crate) static ROTOR_I_TRANSFER_POSITION: Characters = Characters::Q;

/// At this indicated position Rotor II will also step the next rotor in
/// sequence.
pub(crate) static ROTOR_II_TRANSFER_POSITION: Characters = Characters::E;

/// At this indicated position Rotor III will also step the next rotor in
/// sequence.
pub(crate) static ROTOR_III_TRANSFER_POSITION: Characters = Characters::V;

/// At this indicated position Rotor IV will also step the next rotor in
/// sequence.
pub(crate) static ROTOR_IV_TRANSFER_POSITION: Characters = Characters::J;

/// At this indicated position Rotor V will also step the next rotor in
/// sequence.
pub(crate) static ROTOR_V_TRANSFER_POSITION: Characters = Characters::Z;

pub(crate) static ROTOR_I_FORWARD: [Characters; 26] = [
    Characters::E,
    Characters::K,
    Characters::M,
    Characters::F,
    Characters::L,
    Characters::G,
    Characters::D,
    Characters::Q,
    Characters::V,
    Characters::Z,
    Characters::N,
    Characters::T,
    Characters::O,
    Characters::W,
    Characters::Y,
    Characters::H,
    Characters::X,
    Characters::U,
    Characters::S,
    Characters::P,
    Characters::A,
    Characters::I,
    Characters::B,
    Characters::R,
    Characters::C,
    Characters::J,
];

pub(crate) static ROTOR_I_BACKWARD: [Characters; 26] = [
    Characters::U,
    Characters::W,
    Characters::Y,
    Characters::G,
    Characters::A,
    Characters::D,
    Characters::F,
    Characters::P,
    Characters::V,
    Characters::Z,
    Characters::B,
    Characters::E,
    Characters::C,
    Characters::K,
    Characters::M,
    Characters::T,
    Characters::H,
    Characters::X,
    Characters::S,
    Characters::L,
    Characters::R,
    Characters::I,
    Characters::N,
    Characters::Q,
    Characters::O,
    Characters::J,
];

pub(crate) static ROTOR_II_FORWARD: [Characters; 26] = [
    Characters::A,
    Characters::J,
    Characters::D,
    Characters::K,
    Characters::S,
    Characters::I,
    Characters::R,
    Characters::U,
    Characters::X,
    Characters::B,
    Characters::L,
    Characters::H,
    Characters::W,
    Characters::T,
    Characters::M,
    Characters::C,
    Characters::Q,
    Characters::G,
    Characters::Z,
    Characters::N,
    Characters::P,
    Characters::Y,
    Characters::F,
    Characters::V,
    Characters::O,
    Characters::E,
];

pub(crate) static ROTOR_II_BACKWARD: [Characters; 26] = [
    Characters::A,
    Characters::J,
    Characters::P,
    Characters::C,
    Characters::Z,
    Characters::W,
    Characters::R,
    Characters::L,
    Characters::F,
    Characters::B,
    Characters::D,
    Characters::K,
    Characters::O,
    Characters::T,
    Characters::Y,
    Characters::U,
    Characters::Q,
    Characters::G,
    Characters::E,
    Characters::N,
    Characters::H,
    Characters::X,
    Characters::M,
    Characters::I,
    Characters::V,
    Characters::S,
];

pub(crate) static ROTOR_III_FORWARD: [Characters; 26] = [
    Characters::B,
    Characters::D,
    Characters::F,
    Characters::H,
    Characters::J,
    Characters::L,
    Characters::C,
    Characters::P,
    Characters::R,
    Characters::T,
    Characters::X,
    Characters::V,
    Characters::Z,
    Characters::N,
    Characters::Y,
    Characters::E,
    Characters::I,
    Characters::W,
    Characters::G,
    Characters::A,
    Characters::K,
    Characters::M,
    Characters::U,
    Characters::S,
    Characters::Q,
    Characters::O,
];

pub(crate) static ROTOR_III_BACKWARD: [Characters; 26] = [
    Characters::T,
    Characters::A,
    Characters::G,
    Characters::B,
    Characters::P,
    Characters::C,
    Characters::S,
    Characters::D,
    Characters::Q,
    Characters::E,
    Characters::U,
    Characters::F,
    Characters::V,
    Characters::N,
    Characters::Z,
    Characters::H,
    Characters::Y,
    Characters::I,
    Characters::X,
    Characters::J,
    Characters::W,
    Characters::L,
    Characters::R,
    Characters::K,
    Characters::O,
    Characters::M,
];

pub(crate) static ROTOR_IV_FORWARD: [Characters; 26] = [
    Characters::E,
    Characters::S,
    Characters::O,
    Characters::V,
    Characters::P,
    Characters::Z,
    Characters::J,
    Characters::A,
    Characters::Y,
    Characters::Q,
    Characters::U,
    Characters::I,
    Characters::R,
    Characters::H,
    Characters::X,
    Characters::L,
    Characters::N,
    Characters::F,
    Characters::T,
    Characters::G,
    Characters::K,
    Characters::D,
    Characters::C,
    Characters::M,
    Characters::W,
    Characters::B,
];

pub(crate) static ROTOR_IV_BACKWARD: [Characters; 26] = [
    Characters::H,
    Characters::Z,
    Characters::W,
    Characters::V,
    Characters::A,
    Characters::R,
    Characters::T,
    Characters::N,
    Characters::L,
    Characters::G,
    Characters::U,
    Characters::P,
    Characters::X,
    Characters::Q,
    Characters::C,
    Characters::E,
    Characters::J,
    Characters::M,
    Characters::B,
    Characters::S,
    Characters::K,
    Characters::D,
    Characters::Y,
    Characters::O,
    Characters::I,
    Characters::F,
];

pub(crate) static ROTOR_V_FORWARD: [Characters; 26] = [
    Characters::V,
    Characters::Z,
    Characters::B,
    Characters::R,
    Characters::G,
    Characters::I,
    Characters::T,
    Characters::Y,
    Characters::U,
    Characters::P,
    Characters::S,
    Characters::D,
    Characters::N,
    Characters::H,
    Characters::L,
    Characters::X,
    Characters::A,
    Characters::W,
    Characters::M,
    Characters::J,
    Characters::Q,
    Characters::O,
    Characters::F,
    Characters::E,
    Characters::C,
    Characters::K,
];

pub(crate) static ROTOR_V_BACKWARD: [Characters; 26] = [
    Characters::Q,
    Characters::C,
    Characters::Y,
    Characters::L,
    Characters::X,
    Characters::W,
    Characters::E,
    Characters::N,
    Characters::F,
    Characters::T,
    Characters::Z,
    Characters::O,
    Characters::S,
    Characters::M,
    Characters::V,
    Characters::J,
    Characters::U,
    Characters::D,
    Characters::K,
    Characters::G,
    Characters::I,
    Characters::A,
    Characters::R,
    Characters::P,
    Characters::H,
    Characters::B,
];
